#pragma once

//#define RGB_TO_YCBCR_CONVERSION__8BIT_SAMPLE
#define RGB_TO_YCBCR_CONVERSION__GENERAL_KOEF

//#define YCBCR_TO_RGB_CONVERSION__GENERAL
//#define YCBCR_TO_RGB_CONVERSION__NO_ROUNDING
#define YCBCR_TO_RGB_CONVERSION__GENERAL_KOEF

