#pragma once

//#define RGB_TO_YCBCR_CONVERSION__8BIT_SAMPLE
#define RGB_TO_YCBCR_CONVERSION__GENERAL_KOEF

//#define YCBCR_TO_RGB_CONVERSION__GENERAL
//#define YCBCR_TO_RGB_CONVERSION__NO_ROUNDING
#define YCBCR_TO_RGB_CONVERSION__GENERAL_KOEF

#if defined(RGB_TO_YCBCR_CONVERSION__GENERAL_KOEF) || defined(YCBCR_TO_RGB_CONVERSION__GENERAL_KOEF)
//#define IMAGE_CONVERSION_STANDARD_REC_601_BT_601
#define IMAGE_CONVERSION_STANDARD_REC_709_BT_709
#endif
